### ISSUE TITLE
Increase rate limits for subscribing to newsletter

### ISSUE THREAD

**Issue by heatherbooker** [mozmar/basket#12]
Hi! Is there any chance we could change [these rate limits](https://github.com/mozmar/basket/blob/56fdb5217702634f8b0d2294ff1ab62fe874c78c/news/views.py#L60), perhaps just doubling both the number and the time period? I definitely understand not wanting to overwhelm the servers, but allowing changing one's mind once sounds reasonable :) And we do want them to receive the newsletter after all!

This would make [this issue](https://github.com/mozilla/fxa-bugzilla-mirror/issues/238) less likely to occur (though other handling will still be put in place for it.).

If a PR for this would be looked at I would be happy to do that - LMK. Thanks!

**Comment by pmac** [comment]
Hmm. Yeah. We don't really account for people doing a quick sub -> unsub -> sub again dance. I'd be very happy to accept a PR with updated rate limits if you're willing to do that.
