### ISSUE TITLE
Basket HTTPS Only

### ISSUE THREAD

**Issue by pmac** [mozmar/basket#24]
Let's do this. Steps:

## SRE
- [x] Switch health-checks to HTTPS
- [x] Setup redirector service in k8s clusters

## Dev
- [x] Remove code relying on `is_secure`
- [x] Add HTTPs redirector in basket for Deis v1 clusters

**Comment by jgmize** [comment]
All but the last checkbox are done as of now

**Comment by pmac** [comment]
I've checked the last one as I've added the configs to all apps running in all clusters (except Frankfurt, dunno about that one).

**Comment by pmac** [comment]
Deployment to all dev and stage apps is happening now. Once that's done and tested I'll kick off a prod push.

**Comment by pmac** [comment]
All HTTPS redirects behaving as expected. I believe it's time for a prod push.

**Comment by pmac** [comment]
This is done and working fine. Thanks all!
